title: Hoàng Anh Tiến
description: Hoàng Anh Tiến's Personal Website
baseurl: ""

username: Hoàng Anh Tiến
typing_text: Mobile App / Backend Engineer.

email: hoangtien2k3qx1@gmail.com
telegram_username: hoangtien2k3
linkedin_username: hoang-anh-tien-928388193
github_username: hoangtien2k3qx1
facebook_username: hoangtien2k3.vn
instagram_username: hoangtien2k3.vn
viber_number: 0828007853

show_aboutme_card: false
about_me_title: About Me
about_me_description: <empty>

show_skills_card: true
skills_title: Skills

show_timeline_card: true
timeline_title: Experience & Coding C++ / Java OOP
cv_download_link: https://profile-summary-for-github.com/user/hoangtien2k3qx1

show_projects_card: true
show_projects: false
projects_title: Work Projects
show_os_projects: true
os_projects_title: Portfolio Projects

show_contact_card: true
contact_title: Contacts
contact_description: Feel free to contact me wherever is comfortable for you

repository: hoangtien2k3qx1/hoangtien2k3qx1.github.io
github_pages:
  - sorting_algos
  - character_encoder
  - hoangtien2k3qx1.github.io
  
projects:
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
      - hoangtien2k3qx1

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
